### ISSUE TITLE
Manual reordering issue with "add new tabs at end"

### ISSUE THREAD

**Issue by axllent** [atom/tabs#293]
As of Atom 1.6, if the "Add new tabs at end" option is selected, it prevents manual reordering of open tabs. Every time an open tab is dragged to another position and the mouse button released, the tab is then automatically shifted to the end too.

The expected result should only affect **new** tabs (ie: when they are opened).

I'm using Ubuntu Linux.

**Comment by anderoonies** [comment]
this was fixed in #276, just needs to be tested? and pulled in.

**Comment by petemill** [comment]
I'm still seeing this as an issue in 1.7.0-beta5, even in *safe mode*.

**Comment by 50Wliu** [comment]
Fixed by #276.
@petemill Would you mind creating a new issue for that and include your `config.cson`?
