### ISSUE TITLE
Tab bar does not scroll in 1.9.0-beta0

### ISSUE THREAD

**Issue by driskell** [atom/tabs#345]
Interesting issue I have on my Atom Beta 1.9.0-beta0 with tabs 0.98.0.

When I have too many tabs for the width of the window... the tabs are not scrollable.
Interestingly, opening the Find in Files pane I can see the Find and Replace buttons are now off-screen.

Inspecting it seems the width of the tab bar is unconstrained and stretches everything off-screen. Minimap also disappears off screen as tabs are created. I've fiddled around to no avail. Happy to provide more information.

**Comment by driskell** [comment]
<img width="749" alt="screen shot 2016-06-11 at 17 34 23" src="https://cloud.githubusercontent.com/assets/939815/15986242/ca65a5cc-2ffa-11e6-8fb7-4738935e94cc.png">

**Comment by 50Wliu** [comment]
I believe this has been fixed, but I'm not sure what version of Atom the fix will be in.

**Comment by aga5tya** [comment]
I still have this issue on Atom Beta @1.9.0-beta0 with tabs @0.99.0. Cannot scroll the tabs and if i have plenty of tabs open, it hides the active tab beyond the view area.

**Comment by aga5tya** [comment]
@driskell: Happen to figure this one out yet ? i still cannot figure out a way to fix this up, it's annoying since i use too many tabs in atom.

**Comment by driskell** [comment]
I believe @50Wliu means it is an Atom Electron issue. Possibly a bug in flex in the version of Chrome bundled with Atom beta. And that it was fixed but not released.

So my guess is just need to wait for the next beta, or live with it (it is a beta after all.)

**Comment by driskell** [comment]
Or of course, use stable released version.

**Comment by 50Wliu** [comment]
What happened was the new Chrome version in Atom 1.9.0 changed a few of the flexbox rules that made the max width stuff break.  We've fixed that by updating the CSS properties and it looks like the fix should be out in 1.9.0-beta1 (whenever that's released).

**Comment by eclemens** [comment]
I have this issue with version 1.9.9
